name: "Stratum CI Pipeline"

on:
  push:
    branches: [split-arch]
  pull_request:
    branches: [split-arch]

  workflow_dispatch:

concurrency:
  # If workflow for PR or push is already running, stop it and start a new one.
  group: build-${{ github.ref }}
  cancel-in-progress: true

env:
  #---------------------------------------------------------------------
  # Environment variables
  #---------------------------------------------------------------------
  SDE_REPOSITORY: ipdk-io/p4dev.dpdk-sde
  SDE_TAG: 2023.10.1
  SDE_FILENAME: dpdk-sde-dev-ubuntu-20.04.tar.gz
  SDE_INSTALL_DIR: /opt/p4dev/dpdk-sde

  DPDK_TESTLOGS: dpdk-bazel-testlogs.tar.gz

jobs:
  check_stratum_dpdk:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone stratum repository
        uses: actions/checkout@v4
        with:
          path: stratum

      - name: Fetch DPDK SDE
        uses: robinraju/release-downloader@v1.8
        with:
          repository: ${{ env.SDE_REPOSITORY }}
          tag: ${{ env.SDE_TAG }}
          fileName: ${{ env.SDE_FILENAME }}

      - name: Install DPDK SDE
        run: |
          sudo tar -xzf $SDE_FILENAME -C /
          rm $SDE_FILENAME

      - name: Build DPDK Stratum
        working-directory: stratum
        run: |
          export SDE_INSTALL=$SDE_INSTALL_DIR
          bazel build //stratum/hal/bin/tdi/dpdk:stratum_dpdk --define target=dpdk

      - name: Run DPDK unit tests
        working-directory: stratum
        run: |
          export SDE_INSTALL=$SDE_INSTALL_DIR
          xargs -a .github/dpdk-tests.txt bazel test --define target=dpdk --test_tag_filters=-flaky

      - name: Collect unit test logs
        if: failure()
        working-directory: stratum
        run: |
          cd bazel-testlogs
          tar czf $GITHUB_WORKSPACE/$DPDK_TESTLOGS stratum/

      - name: Upload unit test logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          path: $DPDK_TESTLOGS
